const STARTED_STREAM_BEGIN = 'STARTED_STREAM_BEGIN';
const STARTED_STREAM_SUCCESS = 'STARTED_STREAM_SUCCESS';
const STARTED_STREAM_ERROR= 'STARTED_STREAM_ERROR';
const CANCELED_STREAM_BEGIN = 'CANCELED_STREAM_BEGIN';
const CANCELED_STREAM_SUCCESS = 'CANCELED_STREAM_SUCCESS';
const CANCELED_STREAM_ERROR = 'CANCELED_STREAM_ERROR';

const ADD_RECORD = 'ADD_RECORD';


export {
	STARTED_STREAM_SUCCESS,
	STARTED_STREAM_BEGIN,
	STARTED_STREAM_ERROR,
	CANCELED_STREAM_BEGIN,
	CANCELED_STREAM_SUCCESS,
	CANCELED_STREAM_ERROR,
	ADD_RECORD
}


