const SET_NAV_OPEN = 'SET_NAV_OPEN';
const SET_SECONDARY_NAV_OPEN = 'SET_SECONDARY_NAV_OPEN';
const SET_SEARCH_OPEN = 'SET_SEARCH_OPEN';
const SET_IS_MOBILE = 'SET_IS_MOBILE';


export {
	SET_NAV_OPEN,
	SET_SECONDARY_NAV_OPEN,
	SET_SEARCH_OPEN,
	SET_IS_MOBILE
}


